import { DataSource } from 'typeorm';
import { User } from '../../app/entities/user.entity';
import * as bcrypt from 'bcrypt';

export async function seedUsers(dataSource: DataSource) {
  const userRepository = dataSource.getRepository(User);

  // Check if seed users already exist
  const adminExists = await userRepository.findOne({
    where: { email: 'admin@wishzy.com' },
  });

  if (adminExists) {
    console.log('⏭️  Seed users already exist, skipping...');
    return;
  }

  const hashedPassword = await bcrypt.hash('Password@123', 10);

  const users = [
    // Admin users
    {
      email: 'admin@wishzy.com',
      fullName: 'Nguyễn Minh Quân',
      password: hashedPassword,
      role: 'admin',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234567',
      gender: 'male',
      age: 35,
      dob: new Date('1989-05-15'),
      address: 'Quận 1, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=12',
    },
    {
      email: 'admin2@wishzy.com',
      fullName: 'Trần Thu Hà',
      password: hashedPassword,
      role: 'admin',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234568',
      gender: 'female',
      age: 32,
      dob: new Date('1992-08-20'),
      address: 'Cầu Giấy, Hà Nội',
      avatar: 'https://i.pravatar.cc/300?img=5',
    },

    // Instructor users - Diverse backgrounds
    {
      email: 'instructor1@wishzy.com',
      fullName: 'Lê Hoàng Nam',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234569',
      gender: 'male',
      age: 40,
      dob: new Date('1984-03-10'),
      address: 'Hải Châu, Đà Nẵng',
      avatar: 'https://i.pravatar.cc/300?img=13',
    },
    {
      email: 'instructor2@wishzy.com',
      fullName: 'Phạm Thị Lan Anh',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234570',
      gender: 'female',
      age: 38,
      dob: new Date('1986-11-25'),
      address: 'Ninh Kiều, Cần Thơ',
      avatar: 'https://i.pravatar.cc/300?img=9',
    },
    {
      email: 'instructor3@wishzy.com',
      fullName: 'Võ Minh Tuấn',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234571',
      gender: 'male',
      age: 45,
      dob: new Date('1979-07-08'),
      address: 'Lê Chân, Hải Phòng',
      avatar: 'https://i.pravatar.cc/300?img=33',
    },
    {
      email: 'instructor4@wishzy.com',
      fullName: 'Đặng Thị Hương',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'google',
      isInstructorActive: true,
      phone: '0901234572',
      gender: 'female',
      age: 36,
      dob: new Date('1988-12-15'),
      address: 'Nha Trang, Khánh Hòa',
      avatar: 'https://i.pravatar.cc/300?img=20',
    },
    {
      email: 'instructor5@wishzy.com',
      fullName: 'Bùi Văn Đức',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234573',
      gender: 'male',
      age: 42,
      dob: new Date('1982-04-22'),
      address: 'Thành phố Huế',
      avatar: 'https://i.pravatar.cc/300?img=51',
    },
    {
      email: 'instructor6@wishzy.com',
      fullName: 'Hoàng Thị Mai',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234595',
      gender: 'female',
      age: 34,
      dob: new Date('1990-09-10'),
      address: 'Quận 3, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=44',
    },
    {
      email: 'instructor7@wishzy.com',
      fullName: 'Đinh Công Minh',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234596',
      gender: 'male',
      age: 39,
      dob: new Date('1985-06-18'),
      address: 'Hà Đông, Hà Nội',
      avatar: 'https://i.pravatar.cc/300?img=52',
    },
    {
      email: 'instructor8@wishzy.com',
      fullName: 'Ngô Thị Ngọc',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'google',
      isInstructorActive: true,
      phone: '0901234597',
      gender: 'female',
      age: 37,
      dob: new Date('1987-02-28'),
      address: 'Thanh Xuân, Hà Nội',
      avatar: 'https://i.pravatar.cc/300?img=47',
    },
    {
      email: 'instructor9@wishzy.com',
      fullName: 'Ngô Thị Ngọc',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'google',
      isInstructorActive: true,
      phone: '0901234597',
      gender: 'female',
      age: 37,
      dob: new Date('1987-02-28'),
      address: 'Thanh Xuân, Hà Nội',
      avatar: 'https://i.pravatar.cc/300?img=47',
    },
    // Pending instructor (not active yet)
    {
      email: 'instructor.pending@wishzy.com',
      fullName: 'Trịnh Văn Long',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234598',
      gender: 'male',
      age: 33,
      dob: new Date('1991-10-05'),
      address: 'Quận 7, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=60',
    },

    // Regular users - Diverse demographics
    {
      email: 'user1@wishzy.com',
      fullName: 'Nguyễn Văn An',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234574',
      gender: 'male',
      age: 25,
      dob: new Date('1999-01-15'),
      address: 'Quận 1, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=7',
    },
    {
      email: 'user2@wishzy.com',
      fullName: 'Trần Thị Bích',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234575',
      gender: 'female',
      age: 23,
      dob: new Date('2001-05-20'),
      address: 'Quận 3, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=10',
    },
    {
      email: 'user3@wishzy.com',
      fullName: 'Lê Văn Cường',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234576',
      gender: 'male',
      age: 28,
      dob: new Date('1996-03-12'),
      address: 'Tân Bình, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=14',
    },
    {
      email: 'user4@wishzy.com',
      fullName: 'Phạm Thị Diệu',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234577',
      gender: 'female',
      age: 22,
      dob: new Date('2002-08-30'),
      address: 'Quận 7, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=23',
    },
    {
      email: 'user5@wishzy.com',
      fullName: 'Hoàng Văn Em',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234578',
      gender: 'male',
      age: 30,
      dob: new Date('1994-11-10'),
      address: 'Bình Thạnh, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=15',
    },
    {
      email: 'user6@wishzy.com',
      fullName: 'Võ Thị Phương',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234579',
      gender: 'female',
      age: 26,
      dob: new Date('1998-07-25'),
      address: 'Phú Nhuận, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=27',
    },
    {
      email: 'user7@wishzy.com',
      fullName: 'Đặng Văn Giang',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234580',
      gender: 'male',
      age: 24,
      dob: new Date('2000-02-14'),
      address: 'Gò Vấp, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=68',
    },
    {
      email: 'user8@wishzy.com',
      fullName: 'Bùi Thị Hà',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234581',
      gender: 'female',
      age: 27,
      dob: new Date('1997-09-08'),
      address: 'Quận 10, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=26',
    },
    {
      email: 'user9@wishzy.com',
      fullName: 'Đỗ Văn Ích',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234582',
      gender: 'male',
      age: 29,
      dob: new Date('1995-12-20'),
      address: 'Thủ Đức, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=17',
    },
    {
      email: 'user10@wishzy.com',
      fullName: 'Ngô Thị Kim',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234583',
      gender: 'female',
      age: 21,
      dob: new Date('2003-04-18'),
      address: 'Quận 2, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=32',
    },
    {
      email: 'user11@wishzy.com',
      fullName: 'Trương Văn Linh',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234584',
      gender: 'male',
      age: 31,
      dob: new Date('1993-06-05'),
      address: 'Quận 4, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=50',
    },
    {
      email: 'user12@wishzy.com',
      fullName: 'Dương Thị Mai',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234585',
      gender: 'female',
      age: 25,
      dob: new Date('1999-10-12'),
      address: 'Quận 5, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=31',
    },
    {
      email: 'user13@wishzy.com',
      fullName: 'Lý Văn Nam',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234586',
      gender: 'male',
      age: 33,
      dob: new Date('1991-01-22'),
      address: 'Quận 6, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=57',
    },
    {
      email: 'user14@wishzy.com',
      fullName: 'Mạc Thị Oanh',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234587',
      gender: 'female',
      age: 28,
      dob: new Date('1996-08-15'),
      address: 'Quận 8, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=45',
    },
    {
      email: 'user15@wishzy.com',
      fullName: 'Đinh Văn Phúc',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234588',
      gender: 'male',
      age: 26,
      dob: new Date('1998-03-28'),
      address: 'Quận 11, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=69',
    },
    {
      email: 'user16@wishzy.com',
      fullName: 'Hà Thị Quỳnh',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234589',
      gender: 'female',
      age: 24,
      dob: new Date('2000-07-07'),
      address: 'Quận 12, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=43',
    },
    {
      email: 'user17@wishzy.com',
      fullName: 'Cao Văn Rạng',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234590',
      gender: 'male',
      age: 27,
      dob: new Date('1997-11-30'),
      address: 'Bình Tân, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=70',
    },
    {
      email: 'user18@wishzy.com',
      fullName: 'Tăng Thị Sương',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234591',
      gender: 'female',
      age: 29,
      dob: new Date('1995-05-16'),
      address: 'Tân Phú, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=38',
    },
    {
      email: 'user19@wishzy.com',
      fullName: 'Lâm Văn Tài',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234592',
      gender: 'male',
      age: 32,
      dob: new Date('1992-09-25'),
      address: 'Củ Chi, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=56',
    },
    {
      email: 'user20@wishzy.com',
      fullName: 'Vũ Thị Uyên',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234593',
      gender: 'female',
      age: 23,
      dob: new Date('2001-12-10'),
      address: 'Hóc Môn, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=29',
    },
    {
      email: 'user21@wishzy.com',
      fullName: 'Quách Văn Việt',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234594',
      gender: 'male',
      age: 30,
      dob: new Date('1994-04-08'),
      address: 'Nhà Bè, TP. Hồ Chí Minh',
      avatar: 'https://i.pravatar.cc/300?img=11',
    },
  ];

  // Insert directly to bypass @BeforeInsert hook (password already hashed)
  await userRepository
    .createQueryBuilder()
    .insert()
    .into(User)
    .values(users as any)
    .execute();

  console.log(`✅ Successfully seeded ${users.length} users!`);
}
